(function ensightenInit(){var ensightenOptions = {client: "bestbuy", clientId: 2493, publishPath: "privacy_init", bootstrapVersion: "v12", isPublic:0, serverComponentLocation: "nexus.ensighten.com/bestbuy/privacy_init/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/bestbuy/privacy_init/code/", ns: 'bby_privacy', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Apr 09 13:43:55 GMT 2026", beaconSamplingSeedValue: 11, dataLayerName: "ensDataLayer"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(l){function q(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+" is missing"}function r(a){this.name="BeaconException";this.message="There was an error during beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function u(){for(var a=e.dataDefinitionIds.length,b=!0,d=0;d<a;d++){var f=e.dataDefinitions[e.dataDefinitionIds[d]];if(!f||
null==f.endRegistration){b=!1;break}}b&&e.callOnDataDefintionComplete()}var c={},e={};e.ensightenOptions=ensightenOptions;e.scDataObj={};var z="",w=null;if(document.currentScript&&document.currentScript.src){var n=document.currentScript.src;/^[A-Za-z][A-Za-z0-9+.-]*:/.test(n)||(n.startsWith("//")||(n="//"+n),n=window.location.protocol+n);n=new URL(n);z=n.hostname;n=n.pathname;n.startsWith(`/${ensightenOptions.client}/${ensightenOptions.publishPath}/sha`)&&(w=n.split("/"),w=w[w.length-2]||null)}c.version=
"1.26.0";c.getDynamicDomain=function(){if(z)return z;for(var a=null,b=document.getElementsByTagName("script"),d=l.client+"/"+l.publishPath+"/Bootstrap.js",f=l.client+"/Bootstrap.js",h=0;h<b.length;h++)if(-1<b[h].src.indexOf(d)||"prod"==l.publishPath&&-1<b[h].src.indexOf(f)){a=b[h];break}return a?(b=document.createElement("a"),b.href=a.getAttribute("src"),b.hostname):""};ensightenOptions.nexus=c.nexus=ensightenOptions.nexus||c.getDynamicDomain()||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();
c.options={interval:l.interval||100,erLoc:l.errorLocation||c.nexus+"/error/e.gif",scLoc:l.serverComponentLocation||c.nexus+"/"+l.client+"/serverComponent.php",sjPath:l.staticJavascriptPath||c.nexus+"/"+l.client+"/code/",alLoc:l.alertLocation||c.nexus+"/alerts/a.gif",publishPath:l.publishPath,isPublic:l.isPublic,client:l.client,clientId:l.clientId,enableTagAuditBeacon:l.enableTagAuditBeacon,beaconSamplingSeedValue:l.beaconSamplingSeedValue||-1,dataLayerName:l.dataLayerName||"ensDataLayer",protocol:"http:"===
window.location.protocol?window.location.protocol:"https:",sriPath:w};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.appIdWhitelist=[];c.appIdBlacklist=[];window[c.options.dataLayerName]&&window[c.options.dataLayerName][0]&&(window[c.options.dataLayerName][0]["ens.whitelist"]&&(c.appIdWhitelist=window[c.options.dataLayerName][0]["ens.whitelist"]),window[c.options.dataLayerName][0]["ens.blacklist"]&&(c.appIdBlacklist=window[c.options.dataLayerName][0]["ens.blacklist"]));
c.canRuleRunByAppId=function(a){return a?a&&!a.appId||a&&-1==a.appId||0==c.appIdWhitelist.length&&0==c.appIdBlacklist.length?!0:0<c.appIdWhitelist.length&&0==c.appIdBlacklist.length?-1==c.appIdWhitelist.indexOf(a.appId)?!1:!0:0==c.appIdWhitelist.length&&0<c.appIdBlacklist.length?-1==c.appIdBlacklist.indexOf(a.appId)?!0:!1:0<c.appIdWhitelist.length&&0<c.appIdBlacklist.length&&-1==c.appIdBlacklist.indexOf(a.appId)&&-1!=c.appIdWhitelist.indexOf(a.appId)?!0:!1:!1};c.test=function(a){if(c.canRuleRunByAppId(a)&&
!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};q.prototype=Error();q.prototype||(q.prototype={});q.prototype.constructor=q;c.DependencyNotAvailableException=q;r.prototype=Error();r.prototype||(r.prototype={});r.prototype.constructor=r;c.BeaconException=r;c.checkForInvalidDependencies=function(a,b,d,f){for(var h=0;h<d.length;h++)if("DEPENDENCYNEVERAVAILABLE"===d[h])return e.currentRuleId=
a,e.currentDeploymentId=b,e.reportException(new c.DependencyNotAvailableException(f[h])),b&&-1!==b&&c.allDeploymentIds.push(b),!0;return!1};e.currentRuleId=-1;e.currentDeploymentId=-1;e.reportedErrors=[];e.reportedAlerts=[];e.AF=[];c.initialized=!1;e.extend=function(a){c.initialized&&window[ensightenOptions.ns].reportException({name:"CoreExtendException",message:"Core extend was called after initialization"})};e.initialize=function(){c.initialized||(this.extend(c),c.initialized=!0)};e.sampleBeacon=
function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(f){}return a};e.getServerComponent=function(a){e.callOnGetServerComponent();var b=c.options.protocol+"//"+("/"==c.options.scLoc.charAt(0)?c.getDynamicDomain():"")+c.options.scLoc;c.options.sriPath&&(b=b.replace("/serverComponent.php",`/${c.options.sriPath}/serverComponent.php`));a=c.constructScUrl(b,a||!0);fetch(a).then(d=>d.ok?d.json():(window[ensightenOptions.ns].reportException({name:"getServerComponentException",
message:"Network response was not ok"}),{})).then(d=>{c.process(d)}).catch(d=>{window[ensightenOptions.ns].reportException({name:"getServerComponentException",message:"There was a problem with the fetch operation:"+d})})};c.constructScUrl=function(a,b){b=1==b&&"object"==typeof e.scDataObj?e.scDataObj:b;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));var d=window.location.href;if("object"===typeof b)for(i in b&&b.PageID&&(d=b.PageID,delete b.PageID),b){var f=~d.indexOf("#")?d.slice(d.indexOf("#"),
d.length):"";d=d.slice(0,f.length?d.length-f.length:d.length);d+=~d.indexOf("?")?"&":"?";for(k in b)d+=k+"="+b[k]+"&";d=d.slice(0,-1)+f;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";return a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")};c.process=function(a){a.pageFiles&&Array.isArray(a.pageFiles)&&0<a.pageFiles.length&&e.insertPageFiles(a.pageFiles);
a.dataDefinitionIds&&Array.isArray(a.dataDefinitionIds)&&0<a.dataDefinitionIds.length&&e.setPageSpecificDataDefinitionIds(a.dataDefinitionIds);a.context&&(e.context=a.context)};e.setVariable=function(a,b){c.ensightenVariables[a]=b};e.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};e.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};e.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};
e.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=c.options.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(a.rid||e.currentRuleId||-1)+"&did="+encodeURIComponent(a.did||
e.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=e.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a);e.currentRuleId=-1;e.currentDeploymentId=-1};e.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);e.currentRuleId=this.id;e.currentDeploymentId=this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),
c.runRuleIds.push(this.id)),e.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.appId=a.appId;this.executionData={hasRun:!1,runTime:[]}};c.updateRuleEvent=function(a,b){for(var d=0;d<c.ruleList.length;d++)if(null!=c.ruleList[d].eventTriggerObj&&c.ruleList[d].eventTriggerObj.rid==a)return c.ruleList[d].id=a,c.ruleList[d].deploymentId=b,c.ruleList[d].executionData.hasRun=!0,c.ruleList[d].executionData.runTime=[new Date],c.allDeploymentIds.push(b),
c.runDeploymentIds.push(b),c.runRuleIds.push(a),!0;return!1};e.triggerEvent=function(a,b){e.getRule(a)||c.updateRuleEvent(a,b)||window[ensightenOptions.ns].reportException({rid:a,did:b,name:"triggerEvent error",message:"rid not found in rule.eventTriggerObj in registered rule list. Dependent Tag can not run due to missing event object."})};e.registerRule=function(a){if(e.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);e.testAll();return!0};
e.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};e.getRuleList=function(){return c.ruleList};e.clearRuleList=function(){c.ruleList=[]};e.getAllDeploymentIds=function(){return c.allDeploymentIds};e.getRunRuleIds=function(){return c.runRuleIds};e.getRunDeploymentIds=function(){return c.runDeploymentIds};e.hasRuleRun=function(a){return(a=e.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+
a};e.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};e.generateAlert=function(a){a=
e.imageRequest(c.options.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+e.currentRuleId+"&did="+e.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};e.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};e.insertScript=function(a,b,d,f){var h=document.getElementsByTagName("script"),g;if(void 0!==b?b:1)for(g=0;g<
h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(!f)var m=d;else if(d){d=1==d&&"object"==typeof e.scDataObj?e.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;"object"===typeof d&&d.PageID&&(b=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,g.length?b.length-g.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in d)b+=k+"="+d[k]+
"&";b=b.slice(0,-1)+g;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(b)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")}(function(t,p,A){var v=p.head||p.getElementsByTagName("head"),B=function(){if("item"in v){if(!v[0]){setTimeout(B,25);return}v=v[0]}var x=p.createElement("script"),y;for(y in m)x.setAttribute(y,m[y]?m[y]:null);
A&&(x.src=A);x.onload=x.onerror=function(){this.addEventListener&&(this.readyState="loaded")};v.insertBefore(x,v.firstChild)};setTimeout(B,0)})(window,document,a,m)};e.loadScriptCallback=function(a,b,d,f,h){var g=document.getElementsByTagName("script"),m=g[0];h=h||!1;if(d)for(d=0;d<g.length;d++)if(g[d].src===a&&g[d].readyState&&/loaded|complete/.test(g[d].readyState))try{b()}catch(p){window[ensightenOptions.ns].reportException(p)}finally{return}g=document.createElement("script");for(var t in f)g.setAttribute(t,
f[t]?f[t]:null);g.type="text/javascript";g.async=!0;g.src=a;g.onerror=function(){this.addEventListener&&(this.readyState="loaded")};g.onload=g.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(p){window[ensightenOptions.ns].reportException(p)}}};h?(a=document.head||document.getElementsByTagName("head")[0],a.insertBefore(g,a.firstChild)):
m.parentNode.insertBefore(g,m)};e.insertPageFiles=function(a){var b=0,d=0,f=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)if("string"===typeof a[b])window[ensightenOptions.ns].loadScriptCallback(a[b],f);else{const {src:h,integrity:g}=a[b];window[ensightenOptions.ns].loadScriptCallback(h,f,!1,g?{integrity:g,crossorigin:"anonymous"}:{},!0)}};e.unobtrusiveAddEvent=function(a,b,d){try{var f=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,
arguments);return f.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};e.anonymous=function(a,b){return function(){try{e.currentRuleId=b?b:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};e.setCurrentRuleId=function(a){e.currentRuleId=a};e.setCurrentDeploymentId=function(a){e.currentDeploymentId=a};c.bind=function(a,b,d,f,h,g){if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:d||-1,appId:f||-1,dependencies:"immediate"==h?[]:[function(){return window[ensightenOptions.ns].executionState[h]}],
code:a}),null!=g&&(a.eventTriggerObj=g);else if("object"!==typeof a)return!1;e.registerRule(a)};e.bindImmediate=function(a,b,d,f){c.bind(a,b,d,f,"immediate")};e.bindDOMParsed=function(a,b,d,f){c.bind(a,b,d,f,"DOMParsed")};e.bindDOMLoaded=function(a,b,d,f){c.bind(a,b,d,f,"DOMLoaded")};e.bindPageSpecificCompletion=function(a,b,d,f){c.bind(a,b,d,f,"conditionalRules")};e.bindOnGetServerComponent=function(a,b,d,f){c.bind(a,b,d,f,"readyForServerComponent")};e.bindDataDefinitionComplete=function(a,b,d,f){c.bind(a,
b,d,f,"dataDefinitionComplete")};e.checkHasRun=function(a){if(0===a.length)return!0;for(var b,d=0;d<a.length;++d)if(b=e.getRule(parseInt(a[d],10)),!b||!b.executionData.hasRun)return!1;return!0};c.bindDependency=function(a,b,d,f,h,g,m,t){var p=[];if(!c.checkForInvalidDependencies(b,f,d,h)){"immediate"==!m&&p.push(function(){return window[ensightenOptions.ns].executionState[m]});p.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:f||
-1,appId:g||-1,dependencies:p,code:a}),null!=t&&(a.eventTriggerObj=t);else if("object"!==typeof a)return!1;e.registerRule(a)}};e.bindDependencyImmediate=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"immediate")};e.bindDependencyDOMLoaded=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"DOMLoaded")};e.bindDependencyDOMParsed=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"DOMParsed")};e.bindDependencyPageSpecificCompletion=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"conditionalRules")};
e.bindDependencyOnGetServerComponent=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"readyForServerComponent")};e.bindDependencyDataDefinitionComplete=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"dataDefinitionComplete")};e.dataDefinitionIds=[];e.dataDefinitions=[];e.pageSpecificDataDefinitionsSet=!1;e.setPageSpecificDataDefinitionIds=function(a){for(var b=a?a.length:0,d=0;d<b;d++){var f=a[d];if(Array.prototype.indexOf)-1==e.dataDefinitionIds.indexOf(f)&&e.dataDefinitionIds.push(f);else{for(var h=
!1,g=e.dataDefinitionIds.length,m=0;m<g;m++)if(e.dataDefinitionIds[m]===f){h=!0;break}h||e.dataDefinitionIds.push(f)}}e.pageSpecificDataDefinitionsSet=!0;u()};e.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};e.registerDataDefinition=function(a,b){var d=e.dataDefinitions[b];d||(d=new e.DataDefinition(b,
a),e.dataDefinitions[b]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());e.pageSpecificDataDefinitionsSet&&u()};e.callOnDataDefintionComplete=function(){e.executionState.dataDefinitionComplete=!0;e.testAll()};e.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};e.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};e.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};e.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};e.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};e.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};e.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var C=function(){var a=[],b=!1,d=!1;return{add:function(f){b&&!d?f():"function"==typeof f&&(a[a.length]=
f)},exec:function(){d=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};e.new_fArray=function(){return C()};c.timer=null;(function(){function a(f,h){return function(){f.apply(h,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=
a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),e.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",e.callOnDOMParsed,!1),window.addEventListener("load",e.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document,b=function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(b,15);return}window[ensightenOptions.ns].callOnDOMParsed()};b()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(e.executionState.DOMParsed=!0,e.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&e.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,d,f,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],f=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+f,a.push(h);b="["+a.join(";")+"]";var m=c.options.protocol+"//"+c.nexus+"/"+encodeURIComponent(l.client)+"/"+encodeURIComponent(l.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(l.clientId)+"&data="+b+"&idx=0&r="+c.rand;e.imageRequest(m)}catch(t){e.currentRuleId=-1,e.currentDeploymentId=-1,a=
new c.BeaconException(t),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(e.testAll,c.options.interval);return e}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var l=window.performance;if(l){l=l.timing||{};var q=l.navigationStart||0,r={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var u="&ns="+encodeURIComponent(l.navigationStart);for(var c in r)if(void 0!==l[c]){var e=l[c]-q;u+="&"+r[c]+"="+(0<e?encodeURIComponent(e):0)}else u+="&"+r[c]+"=-1";window[ensightenOptions.ns].timing=u;c=ensightenOptions.nexus||"nexus.ensighten.com";l=ensightenOptions.staticJavascriptPath||
"";u=l.indexOf("/",0);q=l.indexOf("/code/");l=l.substring(u,q)+"/perf.rnc";l+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+l)}}});

/*
 MIT License (c) copyright 2013 original author or authors */
window[ensightenOptions.ns].data||(window[ensightenOptions.ns].when=function(){function e(g,l,t,w){return v(g).then(l,t,w)}function B(g){this.then=g}function v(g){return f(function(l){l(g)})}function f(g){function l(z){C&&(x=d(z),b(C,x),C=y)}function t(z){l(k(z))}function w(z){C&&b(C,a(z))}var x,C=[];try{g(l,t,w)}catch(z){t(z)}return new B(function(z,F,G){return f(function(H,N,I){C?C.push(function(L){L.then(z,F,G).then(H,N,I)}):n(function(){x.then(z,F,G).then(H,N,I)})})})}function d(g){return g instanceof
B?g:g!==Object(g)?r(g):f(function(l,t,w){n(function(){try{var x=g.then;"function"===typeof x?T(x,g,l,t,w):l(r(g))}catch(C){t(C)}})})}function r(g){var l=new B(function(t){try{return"function"==typeof t?d(t(g)):l}catch(w){return k(w)}});return l}function k(g){var l=new B(function(t,w){try{return"function"==typeof w?d(w(g)):l}catch(x){return k(x)}});return l}function a(g){var l=new B(function(t,w,x){try{return"function"==typeof x?a(x(g)):l}catch(C){return a(C)}});return l}function b(g,l){n(function(){for(var t,
w=0;t=g[w++];)t(l)})}function c(g,l,t,w,x){p(2,arguments);return e(g,function(C){return f(function(z,F,G){function H(M){P(M)}function N(M){Q(M)}var I;var L=C.length>>>0;var O=Math.max(0,Math.min(l,L));var R=[];var W=L-O+1;var U=[];if(O){var P=function(M){U.push(M);--W||(Q=P=q,F(U))};var Q=function(M){R.push(M);--O||(Q=P=q,z(R))};for(I=0;I<L;++I)I in C&&e(C[I],N,H,G)}else z(R)}).then(t,w,x)})}function h(g,l,t,w){p(1,arguments);return u(g,A).then(l,t,w)}function u(g,l){return e(g,function(t){return f(function(w,
x,C){var z,F;var G=z=t.length>>>0;var H=[];if(G){var N=function(I,L){e(I,l).then(function(O){H[L]=O;--G||w(H)},x,C)};for(F=0;F<z;F++)F in t?N(t[F],F):--G}else w(H)})})}function n(g){1===E.push(g)&&K(m)}function m(){for(var g,l=0;g=E[l++];)g();E=[]}function p(g,l){for(var t,w=l.length;w>g;)if(t=l[--w],null!=t&&"function"!=typeof t)throw Error("arg "+w+" must be a function");}function q(){}function A(g){return g}e.defer=function(){var g,l;var t={promise:y,resolve:y,reject:y,notify:y,resolver:{resolve:y,
reject:y,notify:y}};t.promise=g=f(function(w,x,C){t.resolve=t.resolver.resolve=function(z){if(l)return v(z);l=!0;w(z);return g};t.reject=t.resolver.reject=function(z){if(l)return v(k(z));l=!0;x(z);return g};t.notify=t.resolver.notify=function(z){C(z);return z}});return t};e.resolve=v;e.reject=function(g){return e(g,k)};e.join=function(){return u(arguments,A)};e.all=h;e.map=u;e.reduce=function(g,l){var t=T(V,arguments,1);return e(g,function(w){var x=w.length;t[0]=function(C,z,F){return e(C,function(G){return e(z,
function(H){return l(G,H,F,x)})})};return X.apply(w,t)})};e.any=function(g,l,t,w){return c(g,1,function(x){return l?l(x[0]):x[0]},t,w)};e.some=c;e.isPromise=function(g){return g&&"function"===typeof g.then};B.prototype={otherwise:function(g){return this.then(y,g)},ensure:function(g){function l(){return v(g())}return this.then(l,l).yield(this)},yield:function(g){return this.then(function(){return g})},spread:function(g){return this.then(function(l){return h(l,function(t){return g.apply(y,t)})})},always:function(g,
l){return this.then(g,g,l)}};var y;var E=[];var D=setTimeout;var K="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(g){D(g,0)};var J=Function.prototype;var S=J.call;var T=J.bind?S.bind(S):function(g,l){return g.apply(l,V.call(arguments,2))};J=[];var V=J.slice;var X=J.reduce||function(g){var l=0;var t=Object(this);var w=t.length>>>0;var x=arguments;if(1>=x.length)for(;;){if(l in
t){x=t[l++];break}if(++l>=w)throw new TypeError;}else x=x[1];for(;l<w;++l)l in t&&(x=g(x,t[l],l,t));return x};return e}(),function(){function e(d,r){return v.all(r||[],function(k){return d.apply(null,k)})}function B(d){var r=f.call(arguments,1);return function(){return e(d,r.concat(f.call(arguments)))}}var v=window[ensightenOptions.ns].when;var f=[].slice;v.apply=e;v.call=function(d){return e(d,f.call(arguments,1))};v.lift=B;v.bind=B;v.compose=function(d){var r=f.call(arguments,1);return function(){var k=
f.call(arguments);k=e(d,k);return v.reduce(r,function(a,b){return b(a)},k)}}}(),window[ensightenOptions.ns].data=function(e,B){function v(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var f={engines:{memory:{get:function(a){if(d.utils.isArray(a)){for(var b=[],c=0;c<a.length;c++)b.push(f.data[a[c]]);return e[ensightenOptions.ns].when.resolve(b)}b=f.dataDefinitions[a]||{storage:{get:function(){}}};b=b.storage.get(b);f.data[a]=
b;return e[ensightenOptions.ns].when.resolve(f.data[a])},set:function(a,b){if(d.utils.isArray(a))for(var c in a)f.data[a[c]]=b[c];else f.data[a]=b;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(d.utils.isArray(a))for(var b in a)delete f.data[a[b]];else delete f.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){f.data={};f.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(f.data)}}},
normalizeInputArgs:function(a,b){var c={key:[],val:B},h;if(d.utils.isPlainObject(a))for(h in c.val=[],a)c.key.push(h),c.val.push(a[h]);else d.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},d={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},r=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};
v.prototype=Error();v.prototype||(v.prototype={});v.prototype.constructor=v;f.DataDefinitionException=v;f.checkForInvalidDataDefinitions=function(a){d.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a)),!0):!1};f.collectAvailableDataDefinitions=function(a){for(var b=[],c=0;c<a.length;c++){var h=parseInt(a[c],10),u=e[ensightenOptions.ns].dataDefinitions[h];if(null===u||u===B)if(u=d.storage.session.get({id:h}),
null!==u&&u!==B)d.set(h,u),f.dataDefinitions[h]={id:h,load:"visitor",storage:d.storage.visitor,missingDDFromCache:!0},b.push(e[ensightenOptions.ns].data.get(""+h));else return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Invalid data definition used: "+h)),{promises:[],isInvalid:!0};else b.push(e[ensightenOptions.ns].data.get(""+a[c]))}return{promises:b,isInvalid:!1}};f.getSync=function(a){function b(q){var A=q.extract||h,y=q.transform||u,E=!1,D=null,K=null;try{D=A()}catch(J){D=
null,E=!0}try{K=y(D)}catch(J){K=null,E=!0}E&&c.push(q.id);return K}var c=[],h=function(){return document},u=function(q){return null!==q&&q!==B?q.toString():null},n=parseInt(a);a="string"===typeof a?a.split("."):[];var m={},p="";if(!isNaN(n)&&"undefined"===typeof f.dataDefinitions[n])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(n,"Error resolving data definition: "+n+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(n)&&
"undefined"===typeof f.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),"Data definition specified does not exist on the page";isNaN(n)?3==a.length&&(m=d.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):m=d.getDataDefinitionById(n);p=m.load&&m.load.match(/(session|visitor)/i)&&m.storage&&m.storage.get?m.storage.get(m):
b(m);0<c.length&&e[ensightenOptions.ns].reportException(new f.DataDefinitionException(c,"Error resolving data definitions synchronously: "+c));return p};f.dataDefinitions={};f.dataDefinitionsBySourceCollName={};d.defineEngine=function(a,b){var c=["get","set","remove","clear","all"];f.engines[a]=b;if(!b.returnsPromise)for(a=0;a<c.length;a++){var h=c[a];b[h]=e[ensightenOptions.ns].when.lift(b[h])}};d.storage={instance:{set:function(a,b){},get:function(a){return f.getSync(a.id)}},page:{set:function(a,
b){},get:function(a){return f.data[a.id]}},session:{set:function(a,b){var c=d.storage.session.get({id:a}),h=new Date,u=h.getTime();h.setTime(u+18E5);null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:h.toGMTString()});b={expires:h.getTime(),value:b};e[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var b=e[ensightenOptions.ns].data.cookie.utils.get(a.id),c=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON;c=c||{};var h=new Date;h=h.getTime();if(null===
b){try{var u=c.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(n){u=null}null!=u&&(u.expires=+u.expires,h<=u.expires?b=u.value:""==u.expires&&u.value!=B?b=u.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var c=d.storage.session.get({id:a});null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return d.storage.session.get(a)}}};d.getEngine=
d.engine=function(a){return a?f.engines[a]||{get:r,set:r,remove:r,clear:r,all:r}:f.engines};d.all=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").all()};d.get=function(a,b,c){b=b||"memory";c=c||{};-1<a.indexOf(",")?(a=a.split(","),a=f.normalizeInputArgs(a)):a=f.normalizeInputArgs(a);return c.wait?f.getWait(a.key,e[ensightenOptions.ns].data.engine(b),c):f.data&&f.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(b).get(a.key):f.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(b),
c)};f.getWait=function(a,b,c){var h=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var p=b.get(a);if(-1===c.wait)return p;p.then(function(q){c.setCheck(q)?u.resolve(q):setTimeout(m,c.interval)},function(q){setTimeout(m,c.interval)})},m=function(){var p=+new Date-h;-1!==c.wait&&p<c.wait?n():u.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;d.utils.isArray(a)?c.setCheck=c.setCheck||function(p){for(var q=!0,A=0;A<p.length;A++)q=q&&!!p[A];return q}:c.setCheck=c.setCheck||
function(p){return!!p};n();return u.promise};f.getWaitForKey=function(a,b,c){var h=e[ensightenOptions.ns].when.defer(),u=function(){if(f.data&&f.data.hasOwnProperty(a)){var m=b.get(a);if(-1===c.wait)return m;m.then(function(p){h.resolve(p)},function(p){h.reject(p)})}else setTimeout(n,c.interval)},n=function(){u()};c.interval=c.interval||100;c.wait=c.wait||1;u();return h.promise};d.set=function(a,b,c){var h=f.normalizeInputArgs(a,b);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(c||
"memory").set(h.key,h.val)};d.remove=function(a,b){return e[ensightenOptions.ns].data.engine(b||"memory").remove(a)};d.clear=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").clear()};d.define=function(a,b){b&&(a.name=b.id||b.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};
a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=d.storage[b.toLowerCase()]||d.storage.page;a.resolved=!1;var c=a.extract||function(){return document},h=a.transform||function(p){return p},u=function(p,q){var A=[];A.push(a.persist.set(p,q));a.storage.set(a.id,q);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(p,q,a.collection);e[ensightenOptions.ns].when.all(A).then(function(y){n.resolve(y)},
function(y){n.reject(y)})},n=e[ensightenOptions.ns].when.defer();try{var m=a.trigger()}catch(p){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+p+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),m=e[ensightenOptions.ns].data.bottomOfBodyTrigger()}m.then(function(){var p=n,q=p.resolve,A=e[ensightenOptions.ns].when,y=A.reduce;try{var E=c()}catch(D){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,
'"'+D+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),E=null}q.call(p,y.call(A,[E,function(){try{return h.apply(this,arguments)}catch(D){return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+D+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},u],function(D,K,J,S){a.resolved=!0;if(1==J)return K(D);2==J&&K(a.name,D)}))},function(p){n.reject(p)});f.dataDefinitions[a.id]=a;f.dataDefinitionsBySourceCollName[""+
a.source+"."+a.collection+"."+a.dataDefName]=a;return n.promise};d.checkConditions=function(a){var b,c={lt:function(n,m){var p=+n,q=+m;return isNaN(p)||isNaN(q)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+n+", compareTo: "+m)),!1):p<q},gt:function(n,m){var p=+n,q=+m;return isNaN(p)||isNaN(q)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
n+", compareTo: "+m)),!1):p>q},eql:function(n,m){return n==m},exists:function(n,m){return n===B?!1:!0},re:function(n,m,p){m=new RegExp(m,p?"i":"");try{return n.match(m)}catch(q){return!1}},starts:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,"^"+m,p)},ends:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,m+"$",p)},contains:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,".*"+m+".*",p)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=c.gt;c["is less than"]=
c.lt;c.matches=c.re;for(b=0;b<a.values.length;b++){var h=a.customComparator?a.customComparator[b]?a.customComparator[b]:c[a.comparators[b]]:c[a.comparators[b]],u=h(a.values[b],a.compareTo[b],a.caseInsensitive?a.caseInsensitive[b]||!1:!1);a.not[b]&&(u=!u);if(!u&&h!=c.exists)return!1}return!0};d.triggerPromise=function(a,b,c){c=c||5E3;var h=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var m=a();m!=b?u.resolve(m):+new Date-h<c?setTimeout(n,200):u.reject("timed out")};n();return u.promise};
d.timeoutPromise=function(a,b){var c=e[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};d.delayTrigger=function(a){a=a||10;var b=e[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};d.delayUntilTrigger=function(a,b,c,h){c=c||null;h=h||200;var u=+new Date,n=e[ensightenOptions.ns].when.defer(),m=function(){var p=a();p!=b?n.resolve(p):c?+new Date-u<c?setTimeout(m,h):n.reject("timed out"):
setTimeout(m,h)};m();return n.promise};f.applyTrigger=function(a){var b=e[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};d.immediateTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindImmediate)};d.bottomOfBodyTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};d.whenValueExistsTrigger=function(){return e[ensightenOptions.ns].when.resolve(this.extract())};d.afterEnsightenCompleteTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};
d.afterElementsDownloadedTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};d.getAllDataDefinitionsOnCurrentPage=function(){return f.dataDefinitions};d.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return f.dataDefinitionsBySourceCollName};d.getDataDefinitionById=function(a){return f.dataDefinitions[a||-1]||{}};d.getDataDefinitionBySourceCollectionName=function(a,b,c){return f.dataDefinitionsBySourceCollName[""+a+"."+b+"."+c]||{}};d.getDataDefinitionByPercentSyntax=
function(a){a=(""+a).split("_");return 1>a.length?{}:f.dataDefinitions[a[1]]||{}};d.resolve=function(a,b){var c=this,h=null;if(!f.checkForInvalidDataDefinitions(a))if(b)e[ensightenOptions.ns].bindDataDefinitionComplete(function(){var m=f.collectAvailableDataDefinitions(a);m.isInvalid||e[ensightenOptions.ns].when.all(m.promises).then(function(p){try{b.apply(c,p)}catch(q){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+q))}},
function(p){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+p))})});else{h=[];var u=a;d.utils.isArray(a)||(u=[a]);for(var n=0;n<u.length;n++)h.push(f.getSync(u[n]));return h=d.utils.isArray(a)?h:h[0]}};d.extract=function(a,b){var c="",h=function(){for(var q={},A=e.document.getElementsByTagName("META")||[],y=0,E=A.length;y<E;y++){var D=A[y].name||A[y].getAttribute("property")||"";0!==D.length&&(q[D]=A[y].content)}return q}(),
u=function(q){var A=h[q];if(A)return A;A=e.document.getElementsByTagName("META")||[];for(var y=0,E=A.length;y<E;y++){var D=A[y].name||A[y].getAttribute("property")||"";if(q==D)return A[y].content}},n=function(q){return(val=(new RegExp("&"+q+"=([^&]*)")).exec(e.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},m=function(q){return(val=(new RegExp("^"+q+"=.*|;\\s*"+q+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},p=function(q){(q=getElement(q))&&q.nodeType&&1==q.nodeType&&
(q=q.value||q.innerHTML||"");return q.toString().replace(/\n|\r|\s\s+/g,"")||""};try{return b?"meta"==b?c=u(a):"cookie"==b?c=m(a):"param"==b?c=n(a):"content"==b?c=p(a):"var"==b&&(c=e[a]):c=u(a)||m(a)||n(a)||p(a)||e[a]||"",c||""}catch(q){return""}};d.event_param={};if("undefined"==typeof k)var k={exports:{}};return d}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){var e={},B=window,v,f=Array.isArray||function(k){return"[object Array]"===Object.prototype.toString.call(k)};
e.set=function(k,a){};e.get=function(k){};e.remove=function(k){};e.clear=function(){};try{if("localStorage"in B&&B.localStorage){var d=B.localStorage;e.set=function(k,a){var b,c=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(f(k)){var h=0;for(b=k.length;h<b;h++)d.setItem(k[h],"string"===typeof a[h]?a[h]:c.stringify(a[h]))}else d.setItem(k,"string"===typeof a?a:c.stringify(a))};e.get=function(k){if(f(k)){var a={},b;var c=0;for(b=k.length;c<b;c++)a[k[c]]=d.getItem(k[c]);
return a}return d.getItem(k)};e.remove=function(k){if(f(k)){var a;var b=0;for(a=k.length;b<a;b++)d.removeItem(k[b])}else d.removeItem(k)};e.clear=function(){d.clear()};e.all=function(){return d}}}catch(k){}var r={};for(v in e)r[v]=e[v];r.testStorage=function(){try{var k="tk_"+Math.ceil(5E7*Math.random());r.set(k,"test");if("test"===r.get(k))return r.remove(k),!0}catch(a){}return!1};e.utils=r;return window[ensightenOptions.ns].data.local=e}()),window[ensightenOptions.ns].data.defineEngine("cookie",
function(e,B){var v=function(){return v.get.apply(v,arguments)},f=v.utils={isArray:Array.isArray||function(d){return"[object Array]"===Object.prototype.toString.call(d)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(d){return Array.prototype.slice.call(d)},getKeys:Object.keys||function(d){var r=[],k="";for(k in d)d.hasOwnProperty(k)&&r.push(k);return r},escape:function(d){return String(d).replace(/[,;"\\=\s%]/g,function(r){return encodeURIComponent(r)})},retrieve:function(d,
r){return null==d?r:d},getAllCookies:function(){if(""===e.cookie)return{};for(var d=e.cookie.split("; "),r={},k=0,a=d.length;k<a;k++){var b=d[k].split("=");r[decodeURIComponent(b[0])]=decodeURIComponent(b[1])}return r},set:function(d,r,k){k=k||-1;if(f.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&v.set(a,d[a],r);else if(f.isArray(d)){var b;a=0;for(b=d.length;a<b;a++)v.set(d[a],r[a],k)}else{a=k.expires!==B?k.expires:v.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=f.isPlainObject(a)&&
"toGMTString"in a?";expires="+a.toGMTString():f.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;b=(b=k.path||v.defaults.path)?";path="+b:"";var c=k.domain||v.defaults.domain;c=c?";domain="+c:"";k=k.secure||v.defaults.secure?";secure":"";e.cookie=f.escape(d)+"="+f.escape(r)+a+b+c+k}},get:function(d,r){r=r||B;var k=f.getAllCookies();if(f.isArray(d)){for(var a={},b=0,c=d.length;b<c;b++)a[d[b]]=f.retrieve(k[d[b]],r),a[d[b]]===B&&(a[d[b]]=null);return a}a=f.retrieve(k[d],
r);return a===B?null:a},getGMTString:function(d){var r=new Date;r.setTime(r.getTime()+864E5*d);return r.toGMTString()}};v.defaults={path:"/",expires:f.getGMTString(90)};v.set=function(d,r){f.set(d,r)};v.remove=function(d){d=f.isArray(d)?d:f.toArray(arguments);for(var r=0,k=d.length;r<k;r++)f.set(d[r],"",{expires:-1})};v.clear=function(){return v.remove(f.getKeys(f.getAllCookies()))};v.get=function(d,r){return f.get(d,r)};v.all=function(){return f.getAllCookies()};v.utils=f;return window[ensightenOptions.ns].data.cookie=
v}(document)));
bby_privacy.dataDefinitionIds = [63024,53628];bby_privacy.bindImmediate(function(){var Bootstrapper=window["bby_privacy"];var ensightenOptions=bby_privacy.ensightenOptions;bby_privacy.registerDataDefinition(function(){bby_privacy.data.define({extract:function extractor(){var data=window.track||window.dioPageData||{};return data.missionID||""},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"GS Missions ID",collection:"tag-datalayer",source:"Manage",priv:"false"},{id:"53628"})},53628)},-1,-1,-1);
bby_privacy.bindImmediate(function(){var Bootstrapper=window["bby_privacy"];var ensightenOptions=bby_privacy.ensightenOptions;bby_privacy.registerDataDefinition(function(){bby_privacy.data.define({extract:function extractor(){var pageName=window.dioPageData&&window.dioPageData.pageName||"pageName not found";return pageName},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"sample-definition",collection:"tag-datalayer",source:"Manage",priv:"false"},{id:"63024"})},63024)},-1,-1,
-1);
bby_privacy.bindImmediate(function(){var Bootstrapper=window["bby_privacy"];var ensightenOptions=bby_privacy.ensightenOptions;!function(w,d,x,y){try{w.bby_privacy.getServerComponent=function(){};if(d.location.hostname.includes("test"))d.cookie="privacy_dev\x3dtrue";w.e_dns=/e_dns=1/.test(d.cookie)||w.navigator&&w.navigator.globalPrivacyControl?"1":"0";var s=d.createElement("script"),c=/\/(checkout\/r|cart$|cart\/.*|ihc\/invoice\/)/.test(d.location.pathname),i=c?x:y,a=c?["privacy_prod_cm","privacy_prod_cm_copy"]:["privacy_prod",
"privacy_prod_copy"];d.head.appendChild(s);s.src="https://nexus.ensighten.com/bestbuy/"+a[/privacy_dev=true/.test(d.cookie)?1-i:i]+"/Bootstrap.js"}catch(t){console.log(t)}}(window,document,1,0)},4262617,638325,24);bby_privacy.getServerComponent(bby_privacy.getExtraParams ? bby_privacy.getExtraParams() : undefined);}})();