//tealium universal tag - utag.3 ut4.0.202609021033, Copyright 2026 Tealium.com Inc. All Rights Reserved.
window.criteo_q=window.criteo_q||[];try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;utag.globals=utag.globals||{};if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
if(utag.ut.md5===undefined){md5=function(t,n){var r;if("undefined"!=typeof window&&window.crypto&&(r=window.crypto),!r&&"undefined"!=typeof window&&window.msCrypto&&(r=window.msCrypto),!r&&"undefined"!=typeof global&&global.crypto&&(r=global.crypto),!r&&"function"==typeof require)try{r=require("crypto")}catch(t){}var e=function(){if(r){if("function"==typeof r.getRandomValues)
try{return r.getRandomValues(new Uint32Array(1))[0]}catch(t){}if("function"==typeof r.randomBytes)try{return r.randomBytes(4).readInt32LE()}catch(t){}}throw new Error("Native crypto module could not be used to get secure random number.")},i=Object.create||function(){function t(){}return function(n){var r;return t.prototype=n,r=new t,t.prototype=null,r}}(),o={},s=o.lib={},a=s.Base={extend:function(t){var n=i(this);return t&&n.mixIn(t),n.hasOwnProperty("init")&&this.init!==n.init||(n.init=function(){n.$super.init.apply(this,arguments)}),n.init.prototype=n,n.$super=this,n},create:function(){var t=this.extend();return t.init.apply(t,arguments),t},init:function(){},mixIn:function(t){for(var n in t)t.hasOwnProperty(n)&&(this[n]=t[n]);t.hasOwnProperty("toString")&&(this.toString=t.toString)},clone:function(){return this.init.prototype.extend(this)}},c=s.WordArray=a.extend({init:function(t,n){t=this.words=t||[],this.sigBytes=null!=n?n:4*t.length},toString:function(t){return(t||f).stringify(this)},concat:function(t){var n=this.words,r=t.words,e=this.sigBytes,i=t.sigBytes;if(this.clamp(),e%4)for(var o=0;o<i;o++){var s=r[o>>>2]>>>24-o%4*8&255;n[e+o>>>2]|=s<<24-(e+o)%4*8}else for(o=0;o<i;o+=4)n[e+o>>>2]=r[o>>>2];return this.sigBytes+=i,this},clamp:function(){var n=this.words,r=this.sigBytes;n[r>>>2]&=4294967295<<32-r%4*8,n.length=t.ceil(r/4)},clone:function(){var t=a.clone.call(this);return t.words=this.words.slice(0),t},random:function(t){for(var n=[],r=0;r<t;r+=4)n.push(e());return new c.init(n,t)}}),u=o.enc={},f=u.Hex={stringify:function(t){for(var n=t.words,r=t.sigBytes,e=[],i=0;i<r;i++){var o=n[i>>>2]>>>24-i%4*8&255;e.push((o>>>4).toString(16)),e.push((15&o).toString(16))}return e.join("")},parse:function(t){for(var n=t.length,r=[],e=0;e<n;e+=2)r[e>>>3]|=parseInt(t.substr(e,2),16)<<24-e%8*4;return new c.init(r,n/2)}},h=u.Latin1={stringify:function(t){for(var n=t.words,r=t.sigBytes,e=[],i=0;i<r;i++){var o=n[i>>>2]>>>24-i%4*8&255;e.push(String.fromCharCode(o))}
return e.join("")},parse:function(t){for(var n=t.length,r=[],e=0;e<n;e++)r[e>>>2]|=(255&t.charCodeAt(e))<<24-e%4*8;return new c.init(r,n)}},d=u.Utf8={stringify:function(t){try{return decodeURIComponent(escape(h.stringify(t)))}catch(t){throw new Error("Malformed UTF-8 data")}},parse:function(t){return h.parse(unescape(encodeURIComponent(t)))}},l=s.BufferedBlockAlgorithm=a.extend({reset:function(){this._data=new c.init,this._nDataBytes=0},_append:function(t){"string"==typeof t&&(t=d.parse(t)),this._data.concat(t),this._nDataBytes+=t.sigBytes},_process:function(n){var r,e=this._data,i=e.words,o=e.sigBytes,s=this.blockSize,a=o/(4*s),u=(a=n?t.ceil(a):t.max((0|a)-this._minBufferSize,0))*s,f=t.min(4*u,o);if(u){for(var h=0;h<u;h+=s)this._doProcessBlock(i,h);r=i.splice(0,u),e.sigBytes-=f}
return new c.init(r,f)},clone:function(){var t=a.clone.call(this);return t._data=this._data.clone(),t},_minBufferSize:0}),p=(s.Hasher=l.extend({cfg:a.extend(),init:function(t){this.cfg=this.cfg.extend(t),this.reset()},reset:function(){l.reset.call(this),this._doReset()},update:function(t){return this._append(t),this._process(),this},finalize:function(t){return t&&this._append(t),this._doFinalize()},blockSize:16,_createHelper:function(t){return function(n,r){return new t.init(r).finalize(n)}},_createHmacHelper:function(t){return function(n,r){return new p.HMAC.init(t,r).finalize(n)}}}),o.algo={});return o}(Math);(function(t){var n=md5,r=n.lib,e=r.WordArray,i=r.Hasher,o=n.algo,s=[];!function(){for(var n=0;n<64;n++)s[n]=4294967296*t.abs(t.sin(n+1))|0}();var a=o.MD5=i.extend({_doReset:function(){this._hash=new e.init([1732584193,4023233417,2562383102,271733878])},_doProcessBlock:function(t,n){for(var r=0;r<16;r++){var e=n+r,i=t[e];t[e]=16711935&(i<<8|i>>>24)|4278255360&(i<<24|i>>>8)}
var o=this._hash.words,a=t[n+0],d=t[n+1],l=t[n+2],p=t[n+3],y=t[n+4],g=t[n+5],w=t[n+6],v=t[n+7],_=t[n+8],m=t[n+9],B=t[n+10],x=t[n+11],b=t[n+12],S=t[n+13],H=t[n+14],z=t[n+15],C=o[0],M=o[1],A=o[2],D=o[3];C=c(C,M,A,D,a,7,s[0]),D=c(D,C,M,A,d,12,s[1]),A=c(A,D,C,M,l,17,s[2]),M=c(M,A,D,C,p,22,s[3]),C=c(C,M,A,D,y,7,s[4]),D=c(D,C,M,A,g,12,s[5]),A=c(A,D,C,M,w,17,s[6]),M=c(M,A,D,C,v,22,s[7]),C=c(C,M,A,D,_,7,s[8]),D=c(D,C,M,A,m,12,s[9]),A=c(A,D,C,M,B,17,s[10]),M=c(M,A,D,C,x,22,s[11]),C=c(C,M,A,D,b,7,s[12]),D=c(D,C,M,A,S,12,s[13]),A=c(A,D,C,M,H,17,s[14]),C=u(C,M=c(M,A,D,C,z,22,s[15]),A,D,d,5,s[16]),D=u(D,C,M,A,w,9,s[17]),A=u(A,D,C,M,x,14,s[18]),M=u(M,A,D,C,a,20,s[19]),C=u(C,M,A,D,g,5,s[20]),D=u(D,C,M,A,B,9,s[21]),A=u(A,D,C,M,z,14,s[22]),M=u(M,A,D,C,y,20,s[23]),C=u(C,M,A,D,m,5,s[24]),D=u(D,C,M,A,H,9,s[25]),A=u(A,D,C,M,p,14,s[26]),M=u(M,A,D,C,_,20,s[27]),C=u(C,M,A,D,S,5,s[28]),D=u(D,C,M,A,l,9,s[29]),A=u(A,D,C,M,v,14,s[30]),C=f(C,M=u(M,A,D,C,b,20,s[31]),A,D,g,4,s[32]),D=f(D,C,M,A,_,11,s[33]),A=f(A,D,C,M,x,16,s[34]),M=f(M,A,D,C,H,23,s[35]),C=f(C,M,A,D,d,4,s[36]),D=f(D,C,M,A,y,11,s[37]),A=f(A,D,C,M,v,16,s[38]),M=f(M,A,D,C,B,23,s[39]),C=f(C,M,A,D,S,4,s[40]),D=f(D,C,M,A,a,11,s[41]),A=f(A,D,C,M,p,16,s[42]),M=f(M,A,D,C,w,23,s[43]),C=f(C,M,A,D,m,4,s[44]),D=f(D,C,M,A,b,11,s[45]),A=f(A,D,C,M,z,16,s[46]),C=h(C,M=f(M,A,D,C,l,23,s[47]),A,D,a,6,s[48]),D=h(D,C,M,A,v,10,s[49]),A=h(A,D,C,M,H,15,s[50]),M=h(M,A,D,C,g,21,s[51]),C=h(C,M,A,D,b,6,s[52]),D=h(D,C,M,A,p,10,s[53]),A=h(A,D,C,M,B,15,s[54]),M=h(M,A,D,C,d,21,s[55]),C=h(C,M,A,D,_,6,s[56]),D=h(D,C,M,A,z,10,s[57]),A=h(A,D,C,M,w,15,s[58]),M=h(M,A,D,C,S,21,s[59]),C=h(C,M,A,D,y,6,s[60]),D=h(D,C,M,A,x,10,s[61]),A=h(A,D,C,M,l,15,s[62]),M=h(M,A,D,C,m,21,s[63]),o[0]=o[0]+C|0,o[1]=o[1]+M|0,o[2]=o[2]+A|0,o[3]=o[3]+D|0},_doFinalize:function(){var n=this._data,r=n.words,e=8*this._nDataBytes,i=8*n.sigBytes;r[i>>>5]|=128<<24-i%32;var o=t.floor(e/4294967296),s=e;r[15+(i+64>>>9<<4)]=16711935&(o<<8|o>>>24)|4278255360&(o<<24|o>>>8),r[14+(i+64>>>9<<4)]=16711935&(s<<8|s>>>24)|4278255360&(s<<24|s>>>8),n.sigBytes=4*(r.length+1),this._process();for(var a=this._hash,c=a.words,u=0;u<4;u++){var f=c[u];c[u]=16711935&(f<<8|f>>>24)|4278255360&(f<<24|f>>>8)}return a},clone:function(){var t=i.clone.call(this);return t._hash=this._hash.clone(),t}});function c(t,n,r,e,i,o,s){var a=t+(n&r|~n&e)+i+s;return(a<<o|a>>>32-o)+n}function u(t,n,r,e,i,o,s){var a=t+(n&e|r&~e)+i+s;return(a<<o|a>>>32-o)+n}function f(t,n,r,e,i,o,s){var a=t+(n^r^e)+i+s;return(a<<o|a>>>32-o)+n}function h(t,n,r,e,i,o,s){var a=t+(r^(n|~e))+i+s;return(a<<o|a>>>32-o)+n}n.MD5=i._createHelper(a),n.HmacMD5=i._createHmacHelper(a)}(Math));}else{md5=utag.ut.md5;}
u.generateEventID=function(data){var hash_input=(data["tealium_timestamp_epoch"]||(function(){var d=new Date();return Math.floor(d.getTime()/1000);})())+"-"+id,event_id=md5.MD5(hash_input).toString();return event_id;};u.toBoolean=function(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.isEmptyObject=function(o,a){for(a in o){if(u.hasOwn(o,a)){return false;}}return true;};u.isEmpty=function(o){var t=u.typeOf(o);if(t=="number"){return isNaN(o);}else if(t=="boolean"){return false;}else if(t=="string"){return o.length===0;}else return u.isEmptyObject(o);};u.arrayUnique=function(array){var a=array.concat();for(var i=0;i<a.length;++i){for(var j=i+1;j<a.length;++j){if(a[i]===a[j])a.splice(j--,1);}}return a;};u.ev={"view":1};u.initialized=false;u.scriptRequested=false;u.prep=function(value,alwaysConvert){if(u.typeOf(value)==="string"&&(alwaysConvert||value.indexOf(",")>0)){value=value.replace(/^\s*|\s*$/g,"");}
return value;};u.accountStringToArray=function(accountStr){return accountStr
.split(',')
.map(function(item){return item.trim();});}
u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.copy_ecm_array=function(sourceObj,sourceProp,destObj,destProp){if(!(destObj[destProp]&&u.typeOf(destObj[destProp])=="array"&&destObj[destProp].length>0)){destObj[destProp]=sourceObj[sourceProp].slice(0);}};u.generatePageViewID=function(b){var lookup_id='';lookup_id=b.tealium_random;if(typeof lookup_id!=="undefined"){utag.globals[lookup_id]=window.utag.globals[lookup_id]||{};}else{lookup_id=Math.random().toFixed(16).substring(2);utag.DB("send:3: The tealium_random variable was not defined. Any Criteo OneTag event IDs generated will not be collected by Tealium Collect. Please ensure you are using the latest version of utag.js to generate a tealium_random value.");}
if(b.tealium_random){event_id=u.data.page_view_id||u.generateEventID('page_view',b,lookup_id);if(window.utag.globals[b.tealium_random]){window.utag.globals[b.tealium_random]["criteo_page_view_id"]=event_id;window.utag.globals[b.tealium_random]["criteo_page_view_id_"+id]=event_id;}}else{utag.DB("send:3: Page View ID Generation is enabled, but the tealium_random value was not found in the data layer. No event ID was generated for page_view");}
window.utag.globals[lookup_id]["criteo_page_view_id"]=event_id;u.data.page_view_id=event_id}
function _addToEvent(t_criteo_q,ecm){var temp=[],i,j,_prod;for(i=0;i<u.data.event_list.length;i++){_event=u.data.event_list[i];var g=u.data[_event]=(u.data[_event]||{});g.event=_event;_prod=(u.typeOf(g.item)==="object")?Object.create(g.item):{};u.copy_ecm_array(ecm,"product_id",_prod,"id");u.copy_ecm_array(ecm,"product_unit_price",_prod,"price");u.copy_ecm_array(ecm,"product_quantity",_prod,"quantity");_prod.id=_prod.id||0;switch(_event){case"viewItem":case"viewList":case"viewCategory":case"viewSearchResult":if(g.filters){temp=[];for(j=0;j<g.filters.name.length;j++){temp.push({name:g.filters.name[j],operator:g.filters.operator[j],value:(u.typeOf(g.filters.value[j])==="array"?g.filters.value[j].join(", "):g.filters.value[j])});}
g.filters=temp;}
g.item=g.item||_prod.id;break;case"addToCart":case"viewBasket":case"trackTransaction":temp=[];for(j=0;j<_prod.id.length;j++){temp.push({id:_prod.id[j],price:_prod.price[j],quantity:_prod.quantity[j]});}
g.item=temp;if(_event==="trackTransaction"){g.id=g.id||u.data.transaction_id;}
break;}
if(u.toBoolean(u.data.generatePageView)&&g.item){g.page_view_id=u.data.page_view_id}
t_criteo_q.push(u.clearEmptyKeys(g));}}
u.map={"criteo_id":"account","hashed_email":"email","_sm_3_3":"site_type","fm_segmentation":"viewHome.ui_segment,viewItem.ui_segment,viewList.ui_segment,trackTransaction.ui_segment,viewBasket.ui_segment","browse_node_id":"viewHome.ui_bnid","tealium_event:page_view":"viewHome","tealium_event:homepage":"viewHome","tealium_event:browse_node":"viewHome","tealium_event:view_item_page":"viewItem","tealium_event:search_results_page":"viewList","tealium_event:checkout_page":"trackTransaction","tealium_event:add_to_cart_button":"viewBasket","tealium_event:add_to_watchlist_button":"viewBasket","operational_id":"viewHome.OpID","criteo_custom_quantity":"trackTransaction.item.quantity,viewBasket.item.quantity","criteo_search_results_products":"viewList.item,viewSearchResult.item","guid":"viewItem.ui_guid,viewHome.ui_guid,viewList.ui_guid,trackTransaction.ui_guid,viewBasket.ui_guid","hashed_order_id":"trackTransaction.ui_order_id","criteo_obfuscated_product_price":"trackTransaction.ui_order_value","criteo_category_id":"viewItem.ui_tcat,viewBasket.ui_tcat,trackTransaction.ui_tcat"};u.extend=[function(a,b){try{b['_sm_3_3']="d";}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['tealium_event']!='undefined'&&b['tealium_event'].toString().toLowerCase()=='add_to_cart_button'.toLowerCase())||(typeof b['tealium_event']!='undefined'&&b['tealium_event'].toString().toLowerCase()=='add_to_watchlist_button'.toLowerCase())){try{b['criteo_price_cart_events']=['1']}catch(e){}}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:3");utag.DB(b);var c,d,e,f,h,evt=[],_ecm={};u.data={base_url:"https://dynamic.criteo.com/js/ld/ld.js?a=##account##",account:"",generatePageView:"False",site_type:(function(){return/iPad/.test(navigator.userAgent)?"t":(/Mobile|iP(hone|od)|Android|BlackBerry|IEMobile|Silk/.test(navigator.userAgent)?"m":"d");}()),order_id:"",page_view_id:'',product_id:[],product_quantity:[],product_unit_price:[],event_list:[]};var t_criteo_q=[];for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:3:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){evt=evt.concat(u.map[d].split(","));}}}}
utag.DB("send:3:MAPPINGS");utag.DB(u.data);if(u.data.cusotmer_id&&!u.data.customer_id){u.data.customer_id=u.data.cusotmer_id}
if(!u.data.account){utag.DB(u.id+": Tag not fired: Required attribute account not populated");return;}
var accountArrStr=u.accountStringToArray(u.data.account).join('&a=');u.data.base_url=u.data.base_url.replace("##account##",accountArrStr);u.data.order_id=u.data.order_id||b._corder||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.transaction_id=u.data.transaction_id||u.data.order_id;_ecm.product_id=u.data.product_id;_ecm.product_unit_price=u.data.product_unit_price;_ecm.product_quantity=u.data.product_quantity;if(!u.isEmpty(u.data.account)){var accountArray=u.accountStringToArray(u.prep(u.data.account,false))
t_criteo_q.push({event:"setAccount",account:accountArray});}else{utag.DB("error:3:Criteo Account ID Missing");return;}
if(!u.isEmpty(u.data.site_type)){t_criteo_q.push({"event":"setSiteType","type":u.data.site_type});}
if(!u.isEmpty(u.data.email)){t_criteo_q.push({"event":"setEmail","email":u.prep(u.data.email,true)});}
if(!u.isEmpty(u.data.hashedEmail)){t_criteo_q.push({"event":"setHashedEmail","email":u.prep(u.data.hashedEmail,true)});}
if(!u.isEmpty(u.data.retailer_visitor_id)){t_criteo_q.push({"event":"setRetailerVisitorId","id":u.prep(u.data.retailer_visitor_id,true)});}
if(!u.isEmpty(u.data.customer_id)){t_criteo_q.push({"event":"setCustomerId","id":u.prep(u.data.customer_id,true)});}
if(!u.isEmpty(u.data.zip_code)){t_criteo_q.push({"event":"setZipcode","zipcode":u.prep(u.data.zip_code,true)});}
u.data.event_list=u.data.event_list.concat(evt);u.data.event_list=u.arrayUnique(u.data.event_list);if(u.toBoolean(u.data.generatePageView)){u.generatePageViewID(b);}
_addToEvent(t_criteo_q,_ecm);criteo_q.push(t_criteo_q);if(!u.scriptRequested){u.scriptRequested=true;u.loader({"type":"script","src":u.data.base_url,"loc":"script","id":'utag_3'});}
utag.DB("send:3:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("3","ebay.main"));}catch(error){utag.DB(error);}
