//tealium universal tag - utag.10 ut4.0.202608241406, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.globals=utag.globals||{};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.toBoolean=function(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.isEmptyObject=function(o,a){for(a in o){if(utag.ut.hasOwn(o,a))return false;}
return true;};u.hasgtagjs=function(){window.gtagRename=window.gtagRename||""||"gtag";if(utag.ut.gtagScriptRequested){return true;}
var i,s=document.getElementsByTagName("script");for(i=0;i<s.length;i++){if(s[i].src&&s[i].src.indexOf("gtag/js")>=0&&(s[i].id&&s[i].id.indexOf("utag")>-1)){return true;}}
var data_layer_name=""||"dataLayer";window[data_layer_name]=window[data_layer_name]||[];if(typeof window[window.gtagRename]!=="function"){window[window.gtagRename]=function(){window[data_layer_name].push(arguments);};if(u.data.cross_track_domains!==""){window[window.gtagRename]("set","linker",{domains:u.data.cross_track_domains.split(","),accept_incoming:true});}
window[window.gtagRename]("js",new Date());}
return false;};u.isScriptRequestedInit=false;u.scriptRequestedInit=function(){if(u.isScriptRequestedInit){return}
u.scriptrequested=u.hasgtagjs();u.o=window[window.gtagRename];u.isScriptRequestedInit=true;}
u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.sites={"ecomm":{"required":["prodid"],"params":["prodid","pagetype","totalvalue","category","pvalue","quantity"],"valuerules":["product","cart","purchase"]},"hotel":{"required":["hotelid"],"params":["hotelid","pagetype","checkoutdate","totalvalue"],"valuerules":["cart","purchase"]},"edu":{"required":["pid"],"params":["pid","plocid","pagetype"]},"flight":{"required":["originid","destid"],"params":["originid","destid","pagetype","totalvalue","startdate","enddate"],"valuerules":["cart","purchase"]},"hrental":{"required":["id"],"params":["id","pagetype","startdate","enddate","totalvalue"],"valuerules":["conversionintent","conversion"]},"job":{"required":["id"],"params":["id","locid","pagetype","totalvalue"],"valuerules":["conversionintent","conversion"]},"local":{"required":["id"],"params":["id","pagetype","totalvalue"],"valuerules":["conversionintent","conversion"]},"listing":{"required":["id"],"params":["id","pagetype","totalvalue"],"valuerules":["conversionintent","conversion"]},"travel":{"required":["destid"],"params":["destid","originid","pagetype","startdate","enddate","totalvalue"],"valuerules":["conversionintent","conversion"]},"dynx":{"required":["itemid"],"params":["itemid","itemid2","pagetype","totalvalue"],"valuerules":["conversionintent"]}};u.checkRequired=function(siteName,site){var i,valid=false;if(!u.data[siteName]){return valid;}
for(i=0;i<site.required.length;i++){valid=u.data[siteName][site.required[i]]?true:false;}
return valid;};u.getValue=function(paramName,siteName,site){var i;for(i=0;i<site.valuerules.length;i++){if(u.data.pagetype&&u.data.pagetype===site.valuerules[i]){return u.data[siteName][paramName]||u.data.order_subtotal;}}};u.getParams=function(){var siteName,g={},i;for(siteName in u.sites){var site=u.sites[siteName];if(!u.data[siteName]){continue;}
if(u.checkRequired(siteName,site)){for(i=0;i<site.params.length;i++){if(site.params[i]==="totalvalue"){g[siteName+"_"+site.params[i]]=u.getValue(site.params[i],siteName,site);}else if(site.params[i]==="pagetype"){g[siteName+"_"+site.params[i]]=u.data.pagetype;}else{g[siteName+"_"+site.params[i]]=u.data[siteName][site.params[i]];}}}}
return u.clearEmptyKeys(g);};u.getRemarketingItems=function(){var i,item={},items=[],rmkt=u.data.rmkt,len=0,verticalName,vertical,paramName;if(u.data.product_id.length>0&&!rmkt.retail){rmkt.retail={};rmkt.retail.id=u.data.product_id;}
for(verticalName in rmkt){if(!u.isEmptyObject(rmkt[verticalName])){vertical=rmkt[verticalName];if(verticalName.match(/retail|education|hotel_rental|jobs|local|real_estate|custom/i)&&vertical.id){len=vertical.id.length;}else if(verticalName.match(/flights|travel/i)&&vertical.destination){len=vertical.destination.length;}
for(i=0;i<len;i++){item={};for(paramName in vertical){if(vertical[paramName][i]){item[paramName]=vertical[paramName][i];}}
if(!u.isEmptyObject(item)){item.google_business_vertical=verticalName;items.push(item);}}}}
return items;};u.getItems=function(len){var item={},i,j,items=[],nextLoop=false;items=u.getRemarketingItems();if(u.data.conversion_label){len=len||u.data.product_id.length;for(i=0;i<len;i++){item={};for(j=0;j<items.length;j++){if(items[j].id===u.data.product_id[i]){items[j].price=(u.data.product_unit_price[i]?u.data.product_unit_price[i]:"");items[j].quantity=(u.data.product_quantity[i]?u.data.product_quantity[i]:"");nextLoop=true;break;}}
if(nextLoop){nextLoop=false;continue;}
item.id=u.data.product_id[i];item.price=(u.data.product_unit_price[i]?u.data.product_unit_price[i]:"");item.quantity=(u.data.product_quantity[i]?u.data.product_quantity[i]:"");items.push(item);}}
return items;};u.map={"fm_segmentation":"custom.fm_segment","guid":"custom.guid","browse_node_id":"custom.bn","operational_id":"custom.OpID","hashed_item_id":"purchase.ecomm_prodid","tealium_random":"order_id","tealium_event:homepage":"page_view","tealium_event:browse_node":"page_view","tealium_event:search_results_page":"view_search_results","tealium_event:add_to_cart_button":"add_to_cart","tealium_event:page_view":"page_view","tealium_event:view_item_page":"page_view","tealium_event:checkout_page":"purchase,conversion","item_id":"page_view.ecomm_prodid,add_to_cart.ecomm_prodid","primary_item_id":"product_id","primary_price":"product_unit_price","primary_category_id":"custom.tcat","hashed_order_id":"purchase.transaction_id","google_obfuscated_product_price":"purchase.ecomm_totalvalue","google_ads_id":"conversion_id","google_ads_ecomm_pagetype":"view_search_results.ecomm_pagetype,purchase.ecomm_pagetype,page_view.ecomm_pagetype,add_to_cart.ecomm_pagetype","page_id":"page_id","google_ads_conversion_label":"conversion_label","google_obfuscated_product_core":"purchase.value","currency":"purchase.currency"};u.extend=[function(a,b){try{if((typeof b['tealium_event']!='undefined'&&b['tealium_event'].toString().toLowerCase()=='view_item_page'.toLowerCase())||(typeof b['tealium_event']!='undefined'&&b['tealium_event'].toString().toLowerCase()=='add_to_cart_button'.toLowerCase())||(typeof b['tealium_event']!='undefined'&&b['tealium_event'].toString().toLowerCase()=='add_to_watchlist_button'.toLowerCase())){try{b['google_cart_price']=['1']}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['google_obfuscated_product_core']!='undefined'&&typeof b['google_obfuscated_product_core']!='undefined'&&b['google_obfuscated_product_core']!='')){try{b['google_obfuscated_product_core']=b.google_obfuscated_product_core.reduce((sum,price)=>sum+parseFloat(price),0);}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if(1){switch(b.tealium_event){case'add_to_cart_button':b.yahoo_ea='AddToCart';b.microsoft_ecomm_page_type='cart';b.floodlight_u9='add_to_cart';b.google_ads_ecomm_pagetype='cart';break;case'search_results_page':b.yahoo_ea='Search';b.floodlight_u9='search';b.google_ads_ecomm_pagetype='searchresults'
break;case'view_item_page':b.yahoo_ea='ViewProduct';b.microsoft_ecomm_page_type='product';b.floodlight_u9='page_view';b.google_ads_ecomm_pagetype='product'
break;case'checkout_page':b.yahoo_ea='Purchase';b.microsoft_ecomm_page_type='purchase';b.floodlight_u9='conversion';b.google_ads_ecomm_pagetype='purchase';break;case'homepage':b.yahoo_ea='Homepage';b.google_ads_ecomm_pagetype='homepage';break;case'add_to_watchlist_button':b.yahoo_ea='AddtToWatchlist';b.floodlight_u9='add_to_watchlist';break;case'browse_node':b.yahoo_ea='BrowseNode';b.microsoft_ecomm_page_type='category';b.floodlight_u9='browse';b.google_ads_ecomm_pagetype='browse';break;case'page_view':b.yahoo_ea='Global';b.floodlight_u9='global';b.google_ads_ecomm_pagetype='global';break;default:break;}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:10");utag.DB(b);var c,d,e,f,h,i,j;u.data={"base_url":"https://www.googletagmanager.com/gtag/js","conversion_id":"","conversion_label":"","conversion_value":"","pagetype":"conversion","remarketing":"false","data_layer_name":"","product_id":[],"product_category":[],"product_quantity":[],"product_unit_price":[],"product_discount":[],"rmkt":{},"config":{allow_enhanced_conversions:"false",enable_event_matching_conversions:"false"},"event_data":{"items":[]},cross_track_domains:"",user_data:{},"event":[],"custom":{},transaction_id:'',user_id:'',tealium_random:''};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:10:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){u.data.event=u.data.event.concat(u.map[d].split(","));}}}}
utag.DB("send:10:MAPPINGS");utag.DB(u.data);u.data.tealium_random=b.tealium_random||Math.random().toFixed(16).substring(2);u.scriptRequestedInit();u.data.order_id=u.data.order_id||b._corder||u.data.transaction_id||u.data.tealium_random||"";u.data.order_subtotal=u.data.conversion_value||u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.conversion_currency||u.data.order_currency||b._ccurrency||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(u.data.product_discount.length===0&&b._cpdisc!==undefined){u.data.product_discount=b._cpdisc.slice(0);}
if(u.data.event.length===0&&b._cevent!==undefined){u.data.event=(u.typeOf(b._cevent)==="array")?b._cevent.slice(0):[b._cevent];}
if(typeof(u.data.conversion_id)==="string"&&u.data.conversion_id!==""){u.data.conversion_id=u.data.conversion_id.replace(/\s/g,"").split(",");}
if(typeof(u.data.conversion_label)==="string"&&u.data.conversion_label!==""){u.data.conversion_label=u.data.conversion_label.replace(/\s/g,"").split(",");}
if(typeof(u.data.conversion_cookie_prefix)==="string"&&u.data.conversion_cookie_prefix!==""){u.data.conversion_cookie_prefix=u.data.conversion_cookie_prefix.replace(/\s/g,"").split(",");}
if(u.data.order_currency!==u.data.order_currency.toUpperCase()){u.data.order_currency=u.data.order_currency.toUpperCase();utag.DB("Currency not supplied in uppercase - automatically converting");}
if(!u.data.conversion_id){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
if(u.data.gtag_enable_tcf_support){window["gtag_enable_tcf_support"]=u.toBoolean(u.data.gtag_enable_tcf_support);}
u.o("set",{"developer_id.dYmQxMT":true});for(i=0;i<u.data.conversion_id.length;i++){if(!/^[a-zA-Z]{2}-/.test(u.data.conversion_id[i])){u.data.conversion_id[i]="AW-"+u.data.conversion_id[i];}}
u.data.base_url+="?id="+u.data.conversion_id[0];if(u.data.data_layer_name){u.data.base_url=u.data.base_url+"&l="+u.data.data_layer_name;}
if(!u.scriptrequested||a==='view'){for(i=0;i<u.data.conversion_id.length;i++){if(u.data.conversion_cookie_prefix&&u.data.conversion_cookie_prefix[i]){u.data.config.conversion_cookie_prefix=u.data.conversion_cookie_prefix[i];}
u.o("config",u.data.conversion_id[i],u.data.config);}}
if(u.toBoolean(u.data.config.allow_enhanced_conversions)){u.o('set','user_data',u.data.user_data);}
if(u.toBoolean(u.data.config.enable_event_matching_conversions)){utag.globals[u.data.tealium_random]=utag.globals[u.data.tealium_random]||{};utag.globals[u.data.tealium_random]["google_ec_transaction_id_"+"10"]=u.data.order_id;}
u.data.event_data=u.getParams();u.data.event_data.items=u.getItems();u.data.event_data.user_id=u.data.user_id;utag.ut.merge(u.data.event_data,u.data.custom,1);if(u.data.conversion_label){u.data.event_data.send_to=[];for(i=0;i<u.data.conversion_id.length;i++){u.data.event_data.send_to.push(u.data.conversion_id[i]+"/"+(u.data.conversion_label[i]||u.data.conversion_label[0]));}
if(u.data.order_subtotal){u.data.event_data.value=u.data.order_subtotal;u.data.event_data.currency=u.data.order_currency;}
u.data.event_data.transaction_id=u.data.order_id;u.data.event_data.aw_merchant_id=u.data.aw_merchant_id;u.data.event_data.aw_feed_country=u.data.aw_feed_country;u.data.event_data.aw_feed_language=u.data.aw_feed_language;u.data.event_data.discount=0;for(j=0;j<u.data.product_discount.length;j++){u.data.event_data.discount+=isNaN(parseFloat(u.data.product_discount[j]))?0:parseFloat(u.data.product_discount[j]);}
var containsConversion=false;for(i=0;i<u.data.event.length;i++){if(u.data.event[i]==="conversion"||u.data.event[i]==="purchase"){containsConversion=true;}}
if(!containsConversion&&!u.data.event.length){u.data.event.push("conversion");}}
if(u.toBoolean(u.data.remarketing)){if(!u.data.event.length){u.data.event_data.send_to=u.data.conversion_id;u.data.event.push("page_view");}}
for(i=0;i<u.data.event.length;i++){if(!u.data.event_data.send_to){u.data.event_data.send_to=u.data.conversion_id;}
utag.ut.merge(u.data.event_data,u.data[u.data.event[i]],1);u.o("event",u.data.event[i],u.clearEmptyKeys(u.data.event_data));}
if(!u.hasgtagjs()){u.scriptrequested=true;utag.ut.gtagScriptRequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_10","attrs":{}});}
utag.DB("send:10:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("10","ebay.main"));}catch(error){utag.DB(error);}
